// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDestxaGbcfEzxUk9-lvlq1HPXP-FQW_tQ',
    appId: '1:164738040224:web:246073421532ace54fe4c5',
    messagingSenderId: '164738040224',
    projectId: 'baitaptuan6-b6d02',
    authDomain: 'baitaptuan6-b6d02.firebaseapp.com',
    storageBucket: 'baitaptuan6-b6d02.firebasestorage.app',
    measurementId: 'G-YTKQY1T3ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnBFJGwpDP7XNuc7D4avv81D2f-MFTZ2U',
    appId: '1:164738040224:android:8f7ca150f63861f44fe4c5',
    messagingSenderId: '164738040224',
    projectId: 'baitaptuan6-b6d02',
    storageBucket: 'baitaptuan6-b6d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7J1RzcTPt59pZ85lXQiT-cFCI46qmIzE',
    appId: '1:164738040224:ios:8b2070367c3fc10a4fe4c5',
    messagingSenderId: '164738040224',
    projectId: 'baitaptuan6-b6d02',
    storageBucket: 'baitaptuan6-b6d02.firebasestorage.app',
    iosBundleId: 'com.example.baitapTuan501',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7J1RzcTPt59pZ85lXQiT-cFCI46qmIzE',
    appId: '1:164738040224:ios:8b2070367c3fc10a4fe4c5',
    messagingSenderId: '164738040224',
    projectId: 'baitaptuan6-b6d02',
    storageBucket: 'baitaptuan6-b6d02.firebasestorage.app',
    iosBundleId: 'com.example.baitapTuan501',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDestxaGbcfEzxUk9-lvlq1HPXP-FQW_tQ',
    appId: '1:164738040224:web:fd7520be420eca354fe4c5',
    messagingSenderId: '164738040224',
    projectId: 'baitaptuan6-b6d02',
    authDomain: 'baitaptuan6-b6d02.firebaseapp.com',
    storageBucket: 'baitaptuan6-b6d02.firebasestorage.app',
    measurementId: 'G-EKWDHHCQ0W',
  );
}
